databases:
  - name: serve-at-ease-db
    plan: free

services:
  - type: web
    name: serve-at-ease
    env: python
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120 app:app
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: serve-at-ease-db
          property: connectionString
